name: Build and Release HACS Zip

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update Version in manifest.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.get_version.outputs.VERSION }}\"/g" custom_components/desi/manifest.json

      - name: Inject Domains
        run: |
          sed -i "s/__DESI_WEB_DOMAIN__/${{ secrets.DESI_WEB_DOMAIN }}/g" custom_components/desi/const.py
          sed -i "s/__DESI_API_DOMAIN__/${{ secrets.DESI_API_DOMAIN }}/g" custom_components/desi/const.py

      - name: Create ZIP File for HACS
        run: |
          # 1. GitHub Tag'inden versiyon adını al (örneğin: v.1.0.1)
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # 2. Klasör ve zip adını belirle (home-assistant-test-v.1.0.1 formatında)
          FOLDER_NAME="home-assistant-test-$TAG_NAME"
          
          echo "Oluşturulacak klasör ve zip adı: $FOLDER_NAME"
          
          # 3. Geçici bir dizinde tam istediğin isimde ana klasörü oluştur
          mkdir -p temp_build_dir/$FOLDER_NAME
          
          # 4. Projedeki her şeyi (.git ve geçici dizin hariç) bu klasörün içine kopyala
          rsync -av --exclude='temp_build_dir' --exclude='.git' . temp_build_dir/$FOLDER_NAME/
          
          # 5. Klasörün içine girip tam istediğin yapıda ziple (dışarıya home-assistant-test-v.1.0.1.zip olarak çıkar)
          cd temp_build_dir
          zip -r ../$FOLDER_NAME.zip $FOLDER_NAME/
          cd ..

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Yıldız (*) ile oluşan dinamik isimli zip dosyasını yakalayıp yüklüyoruz
          files: home-assistant-test-*.zip